version: 2.0
jobs:
  build:
    working_directory: ~/hs-arbor-logger
    docker:
      - image: fpco/stack-build:latest

    steps:
      - checkout
      - run: git fetch --unshallow || true
      - run: grep '^resolver:' stack.yaml > resolver.txt

      - restore_cache:
          keys:
            - dot-stack-{{ checksum "stack.yaml" }}-{{ checksum "hs-arbor-logger.cabal" }}
            - dot-stack-{{ checksum "stack.yaml" }}
            - dot-stack-{{ checksum "resolver.txt" }}
            - dot-stack-resolver-{{ checksum "resolver.txt" }}
      - run: stack setup
      - save_cache:
          key: dot-stack-resolver-{{ checksum "resolver.txt" }}
          paths:
            - ~/.stack
      - save_cache:
          key: dot-stack-{{ checksum "stack.yaml" }}
          paths:
            - ~/.stack

      - restore_cache:
          key: stack-work-{{ checksum "stack.yaml" }}
      - run: stack build --test --no-run-tests --dependencies-only
      - save_cache:
          key: dot-stack-{{ checksum "resolver.txt" }}
          paths:
            - ~/.stack

      - run: stack build --test --no-run-tests --haddock --no-haddock-deps
      - save_cache:
          key: dot-stack-{{ checksum "stack.yaml" }}-{{ checksum "hs-arbor-logger.cabal" }}
          paths:
            - ~/.stack
      - save_cache:
          key: stack-work-{{ checksum "stack.yaml" }}
          paths: ~/hs-arbor-logger/.stack-work

      - run:
          name: Running unit tests
          command: stack test
